name: kopia-alt-ui
services:
  kopiaaltui:
    build:
      dockerfile: ./Dockerfile
      context: ../
    ports:
      - 8080:80
    volumes:
      - ./docker/instances.json:/app/config/instances.json
      - ./docker/nginx.conf:/etc/nginx/templates/default.conf.template
